
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=example_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  db: