package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	userFeature "github.com/Sanchir01/sandjma_graphql/internal/feature/user"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
	customMiddleware "github.com/Sanchir01/sandjma_graphql/internal/handlers/middleware"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/api/response"
)

// Login is the resolver for the login field.
func (r *authMutationResolver) Login(ctx context.Context, obj *model.AuthMutation, input *model.LoginInput) (model.LoginResult, error) {
	user, err := r.UserStr.GetUserByPhone(ctx, input.Phone)
	r.Logger.Warn("error getting user by phone", user)
	if err != nil {
		return response.NewInternalErrorProblem("неправильный телефон"), nil
	}

	isValid := userFeature.VerifyPassword(input.Password, user.Password)
	if isValid == false {
		return response.NewInternalErrorProblem("неправильный пароль"), nil
	}

	w := customMiddleware.GetResponseWriter(ctx)
	if err = userFeature.AddCookieTokens(user.ID, user.Role, w); err != nil {
		return response.NewInternalErrorProblem("Error for generating jwt"), nil
	}
	return model.LoginResultOk{User: user}, nil
}
