package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	customMiddleware "github.com/Sanchir01/sandjma_graphql/internal/handlers/middleware"

	userFeature "github.com/Sanchir01/sandjma_graphql/internal/feature/user"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/api/response"
)

// Registration is the resolver for the registration field.
func (r *authMutationResolver) Registration(ctx context.Context, obj *model.AuthMutation, input *model.RegistrationsInput) (model.RegistrationsResult, error) {

	userPhone, _ := r.UserStr.GetUserByPhone(ctx, input.Phone)

	if userPhone != nil {
		r.Logger.Warn("user phone", userPhone)
		return response.NewInternalErrorProblem("User with this phone already exists"), nil
	}
	userEmail, _ := r.UserStr.GetUserByEmail(ctx, input.Email)
	if userEmail != nil {
		r.Logger.Warn("user email", userEmail)
		return response.NewInternalErrorProblem("User with this email already exists"), nil
	}

	newUser, err := r.UserStr.CreateUser(ctx, input)
	if err != nil {
		r.Logger.Warn("user created SUPER", err.Error())
		return response.NewInternalErrorProblem("Error for creating new user"), nil
	}
	w := customMiddleware.GetResponseWriter(ctx)
	if err = userFeature.AddCookieTokens(newUser.ID, newUser.Role, w); err != nil {
		r.Logger.Warn("errors generating jwt", err)
		return response.NewInternalErrorProblem("Error for generating jwt"), nil
	}

	return model.RegistrationsResultOk{User: newUser}, nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type ctxKeyResponseWriter struct{}
