package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	runtime "github.com/Sanchir01/sandjma_graphql/internal/gql/generated"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
)

// Color is the resolver for the color field.
func (r *mutationResolver) Color(ctx context.Context) (*model.ColorMutation, error) {
	return &model.ColorMutation{}, nil
}

// ColorMutation returns runtime.ColorMutationResolver implementation.
func (r *Resolver) ColorMutation() runtime.ColorMutationResolver { return &colorMutationResolver{r} }

type colorMutationResolver struct{ *Resolver }
