package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	featureColor "github.com/Sanchir01/sandjma_graphql/internal/feature/color"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/api/response"
)

// GetAllColors is the resolver for the getAllColors field.
func (r *colorQueryResolver) GetAllColors(ctx context.Context, obj *model.ColorQuery) (model.GetAllColorResult, error) {
	colors, err := r.ColorStr.GetAllColor(ctx)
	if err != nil {
		r.Logger.Error("error getAll color", err.Error())
		return response.NewInternalErrorProblem("error getAll colors"), nil
	}

	colorsMapping, err := featureColor.MapManyColorsToGqlModels(colors)
	return model.GetAllColorOk{Colors: colorsMapping}, nil
}
