package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/api/response"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/utils"
)

// CreateColor is the resolver for the createColor field.
func (r *colorMutationResolver) CreateColor(ctx context.Context, obj *model.ColorMutation, input *model.CreateColorInput) (model.CreateColorResult, error) {
	colorSlug, err := utils.Slugify(input.Name)
	if err != nil {
		r.Logger.Error("error creating color slug", err.Error())
		return response.NewInternalErrorProblem("error creating color slug"), nil
	}
	id, err := r.ColorStr.CreateColor(ctx, input, colorSlug)
	if err != nil {

		return response.NewInternalErrorProblem("error creating color"), nil
	}
	return model.CreateColorOk{Ok: id}, nil
}
