package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	runtime "github.com/Sanchir01/sandjma_graphql/internal/gql/generated"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
)

// Products is the resolver for the products field.
func (r *mutationResolver) Products(ctx context.Context) (*model.ProductMutation, error) {
	return &model.ProductMutation{}, nil
}

// ProductMutation returns runtime.ProductMutationResolver implementation.
func (r *Resolver) ProductMutation() runtime.ProductMutationResolver {
	return &productMutationResolver{r}
}

type productMutationResolver struct{ *Resolver }
