package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/api/response"
)

// CreateProduct is the resolver for the createProduct field.
func (r *productMutationResolver) CreateProduct(ctx context.Context, obj *model.ProductMutation, input *model.CreateProductInput) (model.ProductCreateResult, error) {
	id, err := r.ProductStr.CreateProduct(ctx, input)
	r.Logger.Info("CreateProduct error", input)
	//
	if err != nil {
		return response.NewInternalErrorProblem("Failed to create product"), nil
	}
	r.Logger.Info("create success")

	return model.ProductCreateOk{ID: id}, nil
}
