package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	runtime "github.com/Sanchir01/sandjma_graphql/internal/gql/generated"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
)

// GetAll is the resolver for the getAll field.
func (r *queryResolver) GetAll(ctx context.Context) (*model.ProductsQuery, error) {
	panic(fmt.Errorf("not implemented: GetAll - getAll"))
}

// ProductsQuery returns runtime.ProductsQueryResolver implementation.
func (r *Resolver) ProductsQuery() runtime.ProductsQueryResolver { return &productsQueryResolver{r} }

// Query returns runtime.QueryResolver implementation.
func (r *Resolver) Query() runtime.QueryResolver { return &queryResolver{r} }

type productsQueryResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
