package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/api/response"
	"github.com/Sanchir01/sandjma_graphql/pkg/lib/utils"
)

// CreateSize is the resolver for the createSize field.
func (r *sizeMutationResolver) CreateSize(ctx context.Context, obj *model.SizeMutation, input *model.SizeCreateInput) (model.SizeCreateResult, error) {
	nameSlug, err := utils.Slugify(input.Name)
	if err != nil {
		return response.NewInternalErrorProblem("error creating slug size"), err
	}
	id, err := r.SizeStr.CreateSize(ctx, input, nameSlug)
	if err != nil {
		return response.NewInternalErrorProblem("size already exist"), nil
	}

	return model.SizeCreateOk{Ok: id}, nil
}
