package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	runtime "github.com/Sanchir01/sandjma_graphql/internal/gql/generated"
	"github.com/Sanchir01/sandjma_graphql/internal/gql/model"
)

// Size is the resolver for the size field.
func (r *queryResolver) Size(ctx context.Context) (*model.SizeQuery, error) {
	return &model.SizeQuery{}, nil
}

// SizeQuery returns runtime.SizeQueryResolver implementation.
func (r *Resolver) SizeQuery() runtime.SizeQueryResolver { return &sizeQueryResolver{r} }

type sizeQueryResolver struct{ *Resolver }
